# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=1.0.0
maven_group=com.gammaplus
archives_base_name=GammaPlus

# Dependencies
fabric_version=0.152.2+26.2
cloth_config_version=26.2.155

# Testing
junit_version=5.11.4
