# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=1.2.0
maven_group=com.gammaplus
archives_base_name=GammaPlus

# Dependencies
fabric_version=0.160.6+26.3
cloth_config_version=26.3.158

# Testing
junit_version=5.11.4
